# Trantor Capital
markdown: kramdown

# URL of the Site
url:
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Trantor Capital
# Description of the Site
description: Building and accelerating the future of Web 3.0
# URL of Image of the Site
site-image: https://s2.loli.net/2022/12/12/2mtQv38iAL1zyWY.jpg #/assets/images/meta1.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon 
favicon-url: /assets/images/favicon.png

logo_white:  /assets/images/TRANTOR.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://s2.loli.net/2022/12/12/2mtQv38iAL1zyWY.jpg #/assets/images/meta1.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: contact@trantorside.com
facebook_username:
twitter_username: h3ccapital
instagram_username: 
linkedin_username:
github_username:
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: G-0XY6D583JC

# Disqus
disqus-shortname: Trantor Capital

# Name of the Author
author-name: Trantor Capital
# URL for the Image of the Author
author-image: /assets/images/favicon.png
# 60 Words About the Author
author-about: Trantor Capital is a venture firm that dedicates to the future of Web3. Our team invests in breakthrough ideas, ranging from Blockchain infrastructure to the Metaverse applications. We define ourself as a reliable partner to our portfolio companies, helping them course their way through Web3 world with funding, advising and partnership outreach.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://twitter.com/trantorcap

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ''
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
